// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyCOa5Su8OtqhhABd1DFKqbg8LXUnkAnM',
    appId: '1:358725841692:web:4b0de796d71fb5936740d9',
    messagingSenderId: '358725841692',
    projectId: 'blogs-cf998',
    authDomain: 'blogs-cf998.firebaseapp.com',
    storageBucket: 'blogs-cf998.appspot.com',
    measurementId: 'G-YF9W4WKPKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1jdrZ0JGBPiJMmlNs5ShPVnugoJCYPHY',
    appId: '1:358725841692:android:74b5ad5cf8c0c2536740d9',
    messagingSenderId: '358725841692',
    projectId: 'blogs-cf998',
    storageBucket: 'blogs-cf998.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHmDhz3V7mvVpjZ738l78h2TleUoXP8zU',
    appId: '1:358725841692:ios:4e34909401290da36740d9',
    messagingSenderId: '358725841692',
    projectId: 'blogs-cf998',
    storageBucket: 'blogs-cf998.appspot.com',
    iosBundleId: 'com.example.blog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHmDhz3V7mvVpjZ738l78h2TleUoXP8zU',
    appId: '1:358725841692:ios:4e34909401290da36740d9',
    messagingSenderId: '358725841692',
    projectId: 'blogs-cf998',
    storageBucket: 'blogs-cf998.appspot.com',
    iosBundleId: 'com.example.blog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyCOa5Su8OtqhhABd1DFKqbg8LXUnkAnM',
    appId: '1:358725841692:web:67b088f3a19bd0126740d9',
    messagingSenderId: '358725841692',
    projectId: 'blogs-cf998',
    authDomain: 'blogs-cf998.firebaseapp.com',
    storageBucket: 'blogs-cf998.appspot.com',
    measurementId: 'G-3Q05R2V9X8',
  );
}
